services:
  mitigation-manager:
    build:
      context: .
    container_name: ${MANAGER_CONTAINER_NAME}
    depends_on:
      - nats
    ports:
      - ${MANAGER_PORT}:8000
    command: --debug
    environment:
      - SANIC_NATS_URL=${NATS_URL}
      - SANIC_NATS_TOPIC=${NATS_TOPIC}
      - SANIC_NEO4J_URL=${NEO4J_URL}
      - SANIC_NEO4J_USERNAME=${NEO4J_USERNAME}
      - SANIC_NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - SANIC_SQLITE_DB_PATH=/production.sqlite3
    networks:
      resilmesh_network:
networks:
  resilmesh_network:
    external: true
