services:
  mitigation-manager:
    build:
      context: .
    depends_on:
      - nats
    ports:
    - 8333:8000
    command: --debug
    networks:
      resilmesh_network:
        ipv4_address: 192.168.200.12
  nats:
    image: nats:latest
    ports:
      - 8222:8222
      - 4222:4222
    networks:
      resilmesh_network:
        ipv4_address: 192.168.200.11
networks:
  resilmesh_network:
    external: true
