openapi: 3.0.2
info:
  description: API for executing commands in an OpenC2 Actuator/Consumer
  title: OpenC2 Actuator
  version: 0.0.1
servers:
- description: OpenC2 Actuator API
  url: http://localhost:8889/
paths:
  /api/openc2:
    post:
      description: Send an OpenC2 command to OpenC2 actuator
      operationId: api_openc2_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenC2Response'
          description: Command successfully executed on Actuator
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Unexpected error
      summary: Execute an OpenC2 command
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    OpenC2CommandHeaders:
      example:
        created: 0
        from: from
        to: to
        request_id: request_id
      properties:
        request_id:
          description: ID of a OpenC2 Command Request
          title: request_id
          type: string
        created:
          description: OpenC2 Command creation Timestamp
          title: created
          type: integer
        from:
          description: Hostname or IP of OpenC2 sender
          title: from
          type: string
        to:
          description: Hostname or IP of OpenC2 receiver
          title: to
          type: string
      required:
      - created
      - from
      - request_id
      - to
      title: OpenC2CommandHeaders
      type: object
    OpenC2CommandResponse:
      example:
        status_text: status_text
        results: results
        status: 6
      properties:
        status:
          description: Status code of OpenC2 command execution
          title: status
          type: integer
        status_text:
          description: Status text of OpenC2 command execution
          title: status_text
          type: string
        results:
          description: Results of command execution
          title: results
          type: string
      required:
      - results
      - status
      - status_text
      title: OpenC2CommandResponse
      type: object
    OpenC2Response:
      example:
        command_response:
          status_text: status_text
          results: results
          status: 6
        headers:
          created: 0
          from: from
          to: to
          request_id: request_id
      properties:
        headers:
          $ref: '#/components/schemas/OpenC2CommandHeaders'
        command_response:
          $ref: '#/components/schemas/OpenC2CommandResponse'
      required:
      - command_response
      - headers
      title: OpenC2Response
      type: object
    ErrorMessage:
      example:
        error_message: error_message
        error_code: error_code
      properties:
        error_code:
          title: error_code
          type: string
        error_message:
          title: error_message
          type: string
      required:
      - error_code
      - error_message
      title: ErrorMessage
      type: object
